# Generated by Django 6.0.6 on 2026-06-11 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RangerTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='Rangers/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('RED', 'RED RANGER'), ('YLW', 'YELLOW RANGER'), ('PNK', 'PINK RANGER'), ('BLU', 'BLUE RANGER'), ('GRN', 'GREEN RANGER'), ('GLD', 'GOLDEN RANGER')], max_length=3)),
            ],
        ),
    ]
