# Generated by Django 6.0.6 on 2026-06-14 14:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PowerRangers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangertypes',
            name='type',
            field=models.CharField(choices=[('RED', 'RED RANGER'), ('YLW', 'YELLOW RANGER'), ('PNK', 'PINK RANGER'), ('BLU', 'BLUE RANGER'), ('GRN', 'GREEN RANGER'), ('GLD', 'GOLDEN RANGER'), ('BLK', 'BLACK RANGER')], max_length=3),
        ),
        migrations.CreateModel(
            name='RangerAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilityName', models.CharField(max_length=100)),
                ('abilityEffects', models.TextField()),
                ('ranger_ability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='PowerRangers.rangertypes')),
            ],
        ),
        migrations.CreateModel(
            name='RangerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating_point', models.IntegerField()),
                ('comment', models.CharField(max_length=500)),
                ('date_added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('ran_ger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='PowerRangers.rangertypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RangerStores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(max_length=50)),
                ('storeLocated', models.TextField()),
                ('ranger_type', models.ManyToManyField(related_name='Location_of_Store', to='PowerRangers.rangertypes')),
            ],
        ),
    ]
