# Generated by Django 6.0.6 on 2026-06-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PowerRangers', '0002_alter_rangertypes_type_rangerability_rangerreview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rangerstores',
            old_name='ranger_type',
            new_name='ranger_type_available',
        ),
    ]
